# Generated by Django 3.2.13 on 2022-09-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_ad', models.DateField(auto_now=True)),
            ],
        ),
    ]
